### ISSUE TITLE
vp2room_label.json does not exist

### ISSUE THREAD

**Issue by FreddyBanana** [zehao-wang/LAD#2]
Hello!
Could you please tell me where the "vp2room_label.json" is? 
It seems that the file is not in “datasets/REVERIE/annotations/”.
Thanks~

**Comment by zehao-wang** [comment]
Sorry about missing the file because of the .gitignore -_-! 
Updated in this repo. If find other missing files please let me know.

**Comment by FreddyBanana** [comment]
Thanks for replying~
