### ISSUE TITLE
Questions about reproduction

### ISSUE THREAD

**Issue by SaDil13** [zehao-wang/LAD#3]
Hello! I'm very interested in your work. 
But I'm having some difficulties here. For example, in the **Preprocessing** part, there are some problems with the shell command, like “—clip_save_dir” argument missing {split} to distinguish different h5 files, and in preprocessing code,  h5py.File function should be with parameter a instead of w to avoid overwriting the original file contents, etc. 

Could you please provide us with the **preprocessed** file? It would help me a lot to our subsequent reproduction.

Thanks a lot~

**Comment by Mingxiao-Li** [comment]
> Hello! I'm very interested in your work. But I'm having some difficulties here. For example, in the **Preprocessing** part, there are some problems with the shell command, like “—clip_save_dir” argument missing {split} to distinguish different h5 files, and in preprocessing code, h5py.File function should be with parameter a instead of w to avoid overwriting the original file contents, etc.
> 
> Could you please provide us with the **preprocessed** file? It would help me a lot to our subsequent reproduction.
> 
> Thanks a lot~
 
Hi, thanks for your interest.  You can see lines 27/28 in ge_ins2img_feat.py:
SPLITS_SOON = ["val_unseen_house","val_unseen_instrs","test","train"]
SPLIT_REVERIE = ["val_unseen","val_seen","train","test"]
and in line 276, we list all splits in SPLIT_SOON/REVERIE. By default we preprocess all splits in one run, thus we do not pass a split parameter from args.

**Comment by zehao-wang** [comment]
For preprocessed files, we are sorry that we do not have large enough online drive -_-!

**Comment by SaDil13** [comment]
Thanks for your replying ^_^!

**Comment by zehao-wang** [comment]
> Thanks for your replying ^_^!
> 
Hi 
I try to cleanup some storage and put the files on the drive now. You can find the checkpoint of warmup stage 2 at [here](https://drive.google.com/drive/folders/177YBl9eNtPjmmB6E18LMAvFM6bh1keTa?usp=share_link) and our extracted features at [here](https://drive.google.com/drive/folders/10xrt1iv38UC3mS0JtmoKhEMPItJ3Atbz?usp=share_link)

Hope this can help to reproduce the results.

**Comment by SaDil13** [comment]
Thanks so much！That is of great help to me ^ ^!
