### ISSUE TITLE
sim.setRenderingEnabled(False)

### ISSUE THREAD

**Issue by FreddyBanana** [zehao-wang/LAD#5]
Hello！

I probably have found the error in my reproduction: 

Since the Linux server I am using does not have a GUI, I have added "sim.setRenderingEnabled(False)" to the "get_all_imgs_fts.py" to disable the graphic rendering of MatterSim. The reason for adding "sim.setRenderingEnabled(False)" is that I found the code of DUET is also added.

I think that's the problem here. 

I noticed that "state.rgb" is used in "get_all_imgs_fts.py", which is different from DUET.

Is there a problem here?

**Comment by zehao-wang** [comment]
We also use Linux cluster without a display, I am not sure about your comment. You can check whether the extracted images are correct.

**Comment by FreddyBanana** [comment]
Won't you report the following error when running 'get_all_imgs_fts. py', if you use Linux cluster without a display? 
![59559f2d60d2f574220aadbf8480341](https://user-images.githubusercontent.com/94211241/233533469-806adfe6-1a80-4500-99c6-40e4e0dfd3b5.jpg)
Or perhaps you have used the correct virtual graphical interface.
I have tried using VNC or Xvfb to solve this graphical interface problem, but they all ended up with this error：
![capture_20230421113616556](https://user-images.githubusercontent.com/94211241/233535160-6e7e2634-2c5e-46d4-a7fc-6822428f24b5.jpg)
May I ask how you solved this problem? It has bothered me for a long time. :sob:

**Comment by zehao-wang** [comment]
I haven't met such problem. It seems the problems are from Matterport3DSimulator, you can check issues from their repo. Probably you can try their examples in the README to make sure you have correctly setup the docker. From my experience, the applications built on this simulator are always quite complex, try to debug step-by-step

**Comment by FreddyBanana** [comment]
Problem solved！:v:

**Comment by zhangjb416** [comment]
> Problem solved！✌️

Hi! I have met similar problems. May I ask how do you solve your problem?
When I set sim.setRenderingEnabled(True) as in DUET, this error happens when sim.initialize() is called:  "fails with EGL error 0x3001".
However, if I set sim.setRenderingEnabled(False), the "state.rgb" commands output an array of zeros for the images...
Do you have any idea of this problem? Thanks a lot!

**Comment by FreddyBanana** [comment]
> > Problem solved！✌️
> 
> Hi! I have met similar problems. May I ask how do you solve your problem? When I set sim.setRenderingEnabled(True) as in DUET, this error happens when sim.initialize() is called: "fails with EGL error 0x3001". However, if I set sim.setRenderingEnabled(False), the "state.rgb" commands output an array of zeros for the images... Do you have any idea of this problem? Thanks a lot!

You should set sim.setRenderingEnabled(True).
And I think "fails with EGL error 0x3001" is related to Matterport3DSimulator, you can try cmaking it again, just follow the instructions in [https://github.com/peteanderson80/Matterport3DSimulator](url).

**Comment by zhangjb416** [comment]
> 

Thanks! I solved this problem by cmaking again!
