### ISSUE TITLE
When I run the get_all_imgs_fts .py, I met a question.

### ISSUE THREAD

**Issue by Wang1665941855** [zehao-wang/LAD#7]
![image](https://github.com/zehao-wang/LAD/assets/125247337/dbe1124d-7569-480e-97b1-24f01f18fa98)

**Comment by zehao-wang** [comment]
you can find the files under connectivity folder in matterport3dSimulator : https://github.com/peteanderson80/Matterport3DSimulator/tree/master/connectivity

**Comment by Wang1665941855** [comment]
Thank you for your reply.  I set the GRAPHTS  = "/root/mount/LAD/datasets/R2R/connectivity/" , this path also have scans.txt,
the dataset_path =  "/root/mount/LAD/mp3d/v1/scans" is setting true,  But the code keeps reporting this error。

**Comment by zehao-wang** [comment]
Probably you need to first try whether you can visit the file in the environment of your python script (docker? I guess), maybe the environment variable in the docker is not correctly set.

**Comment by Wang1665941855** [comment]
YES， I used docker.  thanks, I try again.
