### ISSUE TITLE
About how to get the vp2room file

### ISSUE THREAD

**Issue by xiongfy** [zehao-wang/LAD#8]
Hello, I would like to ask you about how the room type in the vp2room file provided is obtained from the simulator. Looking forward to your reply, thank you!

**Comment by zehao-wang** [comment]
You can refer to https://aihabitat.org/docs/habitat-sim/habitat_sim.scene.SemanticScene.html

The 'levels' in the simulator if I remember correctly refers to the room annotation. You can go through the semantic scene attributes to check all the labels converted from semantic mesh. You can also refer to semantic mesh file (usually the ply file), matterport has all the annotations for each single mesh.
